# Operation Mode
# Note: These are typically set automatically based on other flags
mode: null  # Can be a combination of SEQUENCE, GEOMETRY, TOPOLOGY, FIBRIL, MIX, REPLACE

# General Configuration
config_file: null  # Path to this YAML configuration file
debug: false

# Sequence Generation Configuration
sequence_generator: false
fasta_file: homosapiens.fasta
output_prefix: "my_collagen_sequence"
species: "Homo_sapiens"
crosslink: true
n_term_type: "HLKNL"
c_term_type: "HLKNL"
n_term_combination: "9.C - 947.A"
c_term_combination: "1047.C - 104.C"

# Geometry Generation Configuration
geometry_generator: true
file: human-D.pdb  # Input PDB file. Note: Comment this line if sequence_generator is true
output: "collagen_human"
working_directory: "./"
contact_distance: 60
fibril_length: 334.0
crystalcontacts_file: null # crystalcontacts_from_colbuilder.txt
connect_file: null
crystalcontacts_optimize: false # Note: This is always true when generating geometry from contact_distance, but has to be set to true to be performed otherwise.

# Mix Configuration
mix_bool: true
ratio_mix: "D:70 T:30"
files_mix: 
  - "human-D.pdb"
  - "human-T.pdb"

# Replace Configuration
replace_bool: false
ratio_replace: 30
replace_file: null

# Topology Generation Configuration
topology_generator: true
force_field: amber99 # Note: Choose between "amber99" and "martini"

